### ISSUE TITLE
Blocking mouse events only in a place that is not a hole

### ISSUE THREAD

**Issue by yegor-pelykh** [TabooSun/overlay_tutorial#43]
It is needed to make the entire surface of the overlay opaque for mouse events (blocking the passing of events under it), but at the same time, so that mouse events pass through the hole, that is, the element in the hole is clickable.

Also need a callback for the mouse event when the user taps on the surface of the overlay that is not a hole (like `onTap` from `GestureDetector`)

I would say, this is a continuation of topic https://github.com/TabooSun/overlay_tutorial/issues/42.

**Comment by TabooSun** [comment]
I still don't see how I can help you here. This package is not designed to handle blocking event pointer; at least, at this moment. The reason for this is to provide flexibility to you as a developer to write the code however you want.

If I understand you correctly, you have a few other elements that accept event pointer but are not being cropped as a hole; there is also a "close button" where you want it to be cropped as a hole and expect it to accept pointer for `onPressed` callback. In this case, you should make sure the "close button" has no `AbsorbPointer` as an ancestor otherwise the "close button" won't work as you have already blocked it.

**Comment by yegor-pelykh** [comment]
Your package is designed to show a guide to controls on the screen. But if at the moment when the guide is shown, the user clicks on the overlay, and the button below it fires some event, is this an acceptable situation for you? I would say no. At least for most users. Therefore, I would say that the package should be designed for this as well.

I need to make a fab that, when clicked, will open this overlay, while being in the hole of this overlay itself, remaining functional in order to close the overlay again by clicking on the fab.
But also, when the user clicks on the overlay elsewhere, I want the overlay to close in the same way as if we clicked on this fab.

**Comment by TabooSun** [comment]
I am still struggling to understand what you want to achieve here. Would you be able to provide a minimum reproducible code to help me out?

**Comment by yegor-pelykh** [comment]
I already, like, have described clearly enough.
But apparently, you are not ready to help in this anyway, so I do not want to waste time on this.

No more questions 🙂
